### PR TITLE
Version#2 of the product pojo, now with one to many mapped by! also adjusted the nam…

### PR DESCRIPTION
**Pull request by JoelD95**
…e field to productName for clarity

### CODE REVIEW

**Review by RayXia95 — CHANGES_REQUESTED** [review]
everything looks good, but I think the POJO should have a to string method

**Comment by JoelD95** [comment]
oh yup forgot to add that

**Review by RayXia95 — CHANGES_REQUESTED** [review]
The one to many fields on both of them should be a List of Purchases and a list of Selling

**Comment by JoelD95** [comment]
wouldn't that be a method?

**Comment by RayXia95** [comment]
What would be a method?. The state of a product cant have many purchasers and sellers. So that why it should be a list.

**Comment by JoelD95** [comment]
like for reimbursements in our ERS, those were methods

**Comment by RayXia95** [comment]
Do you mean that once the tables is initialized and that it would just be a method in hibernate to get a list of them? That is just an inner join behind the scenes, but the POJO needs a state of people that are buying the product and that are selling the product

**Comment by JoelD95** [comment]
ah ok

**Review by RayXia95 — CHANGES_REQUESTED** [review]
The list should not be of users it should be of Purchases and Selling because those junction table has the ID of the User

**Review by RayXia95 — CHANGES_REQUESTED** [review]
could you also delete the super() in the constructor and make sure in between methods and constructors that there are only one lines between each one

**Review by RayXia95 — APPROVED** [review]

**Pull request merged**
