### PR TITLE
users can buy things now.Had to modify the purchase model to include …

### PR DESCRIPTION
**Pull request by JoelD95**
…a cascade on both users and product

### CODE REVIEW

**Comment by mfleres** [comment]
Have you tested in Postman?

**Comment by JoelD95** [comment]
yes sir with these parameters:
{
	"cost": 750,
	"time": {{$timestamp}},
	"quantity":1,
	"buyer": {"username": "jdoe",
"email": "jdoe@gmail.com",
"firstName": "John",
"lastName":"Doe",
"password": "hashed",
"street": "12 Main St.",
"town": "Princeton",
"state": "NJ",
"zipCode": "08540"},
	"product":{"description":"this is an Android",
		"productName":"Android",
		"image":"image.com"
	}
	
}

**Review by RayXia95 — CHANGES_REQUESTED** [review]
All of this looks good. Did you test this out with mvn clean install?

**Comment by JoelD95** [comment]
i have not tested it with clean install

**Review by RayXia95 — APPROVED** [review]

**Pull request merged**
