### PR TITLE
Feature/transaction pojo

### PR DESCRIPTION
**Pull request by mfleres**
Uses both the User and Product POJOs.

### CODE REVIEW

**Review by RayXia95 — CHANGES_REQUESTED** [review]
This looks good, but my only concern is the driver class. Web projects should not have a driver class.

**Comment by mfleres** [comment]
I have removed the Driver

**Review by RayXia95 — APPROVED** [review]

**Comment by RayXia95** [comment]
Could you also put the constructor after all the instance variable. After that everything will be fine

**Comment by mfleres** [comment]
Moved the constructor.

**Comment by mfleres** [comment]
Added constructor with args.

**Comment by mfleres** [comment]
Removed super()

**Pull request merged**
